// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a key combination (key + modifiers)
 */
export type KeyCombination = { code: string, modifiers: number, };
