// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementAction } from "./ElementAction";
import type { KeyCombination } from "./KeyCombination";

export type ElementKeyBinding = { key: KeyCombination, action: ElementAction, };
