// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementKeyBinding } from "./ElementKeyBinding";

export type Element = { tag: string, classes: Array<string>, attributes: { [key in string]?: string }, content: string | null, children: Array<Element>, id: string | null, focusable: boolean, focused: boolean, disabled: boolean, tab_index: number | null, key_bindings: Array<ElementKeyBinding>, modal: boolean, };
