name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            name: darwin-x64
          - host: windows-latest
            target: x86_64-pc-windows-msvc  
            name: win32-x64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: linux-x64-musl
          - host: macos-latest
            target: aarch64-apple-darwin
            name: darwin-arm64
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-arm64
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            name: linux-arm64-musl
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            name: win32-arm64

    name: Build ${{ matrix.settings.name }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
          cache: npm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --target ${{ matrix.settings.target }}
        shell: bash

      - name: Test
        run: npm test
        if: ${{ !contains(matrix.settings.target, 'musl') }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.name }}
          path: |
            reactive-tui.*.node
            index.js
            index.d.ts

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifacts
        run: |
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              cp "$dir"/*.node . 2>/dev/null || true
            fi
          done

      - name: List package files
        run: |
          echo "Package contents:"
          ls -la *.node || echo "No .node files found"
          ls -la index.js index.d.ts

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, publish]

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/**/*.node
            artifacts/**/index.js
            artifacts/**/index.d.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}