name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-release:
    name: Check if release is needed
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.semantic.outputs.should-release }}
      version: ${{ steps.semantic.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check for semantic release
        id: semantic
        run: |
          # Run semantic-release in dry-run mode and capture output
          OUTPUT=$(npx semantic-release --dry-run 2>&1)
          echo "$OUTPUT"

          # Check if a new release would be published
          if echo "$OUTPUT" | grep -q "The next release version is"; then
            echo "should-release=true" >> $GITHUB_OUTPUT
            VERSION=$(echo "$OUTPUT" | grep "The next release version is" | sed 's/.*The next release version is \([0-9.]*\).*/\1/')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Release needed: $VERSION"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "No release needed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build ${{ matrix.settings.name }}
    runs-on: ${{ matrix.settings.host }}
    needs: check-release
    if: needs.check-release.outputs.should-release == 'true'
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            name: darwin-x64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            name: win32-x64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: linux-x64-musl
          - host: macos-14
            target: aarch64-apple-darwin
            name: darwin-arm64
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-arm64
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            name: linux-arm64-musl

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Install cross-compilation tools
        if: contains(matrix.settings.target, 'aarch64-unknown-linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install musl tools
        if: contains(matrix.settings.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev

      - name: Install musl cross-compilation tools
        if: matrix.settings.target == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --target ${{ matrix.settings.target }}
        shell: bash
        env:
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CC_aarch64_unknown_linux_musl: aarch64-linux-gnu-gcc
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.name }}
          path: |
            reactive-tui.*.node
            index.js
            index.d.ts

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [check-release, build]
    if: needs.check-release.outputs.should-release == 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifacts
        run: |
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              cp "$dir"/*.node . 2>/dev/null || true
            fi
          done

      - name: List package files
        run: |
          echo "Package contents:"
          ls -la *.node || echo "No .node files found"
          ls -la index.js index.d.ts

      - name: Create dist directory for semantic-release
        run: |
          mkdir -p dist
          npm pack --pack-destination=dist

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

